site_name: Metamorf
nav:
  - Index: index.md
  - Architecture: architecture.md
  - Set up: setup.md
  - Commands: commands.md
  - Version Features: version_features.md
  - Roadmap: roadmap.md
  - Contact: contact.md

theme: 
    name: material
    language: en
    logo: images/logo-white.png
    favicon: images/logo.png
    palette:
      scheme: slate
      primary: teal
      accent: cyan
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gasalom/metamorf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/guillermo-aumatell-038357146/
  